hunter_config(OpenCV VERSION 3.2.0-p1
    CMAKE_ARGS
        BUILD_SHARED_LIBS=OFF
        WITH_OPENCL=OFF
        WITH_OPENEXR=OFF
        BUILD_DOCS=OFF
        OPENCV_WITH_EXTRA_MODULES=YES
        CMAKE_POSITION_INDEPENDENT_CODE=ON
        )
